name: CICD PIPELINE

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
    -  name: Checkout Repo
       uses: actions/checkout@v4

    -  name: Welcome Message
       run: echo "This is a pipeline for Netflix clone App"

    - name: List Files
      run: ls

    - name: Read file
      run: cat README.md
