name: Generate ASCII Artwork

on:
    push

jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        -   name: Install Cowsay Program
            run: sudo apt-get install cowsay -y

        -   name: Execute Cowsay CMD
            run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

        -   name: Sleep for 30 seconds
            run: sleep 30

    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        -   name: Sleep for 10 seconds
            run: sleep 10
        
        -   name: Test File Exists
            run: grep -i "dragon" dragon.txt

    deploy_job_3:
        needs: [test_job_2]  # You can define the jobs it needs as an array if they are more than one, I only used the array here for example and as part of my documentation
        runs-on: ubuntu-latest
        steps:
        -   name: Read File
            run: cat dragon.txt

        -   name: Deploy
            run: echo Deploy ... ... ... ...

        
        # -   name: Checkout Repo
        #     uses: actions/checkout@v4

        # -   name: List Repo Files
        #     run: ls -ltra

        # - name: Executing Shell Script
        #   run: |
        #     chmod +x script.sh
        #     ./script.sh

        # -   name: Install Cowsay Program
        #     run: sudo apt-get install cowsay -y

        # -   name: Execute Cowsay CMD
        #     run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt
        
        # -   name: Check if Test File Exists
        #     run: grep -i "dragon" dragon.txt

        # -   name: Read file
        #     run: cat dragon.txt


